config/routes.rb
Rails.application.routes.draw do
  
  
  get 'relationships/create'
  get 'relationships/destroy'
  get 'create/destroy'
  get 'home/about', to: 'homes#about', as: 'about'
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:create, :index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
  end
  resources :chats, only: [:show, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :read_counts, dependent: :destroy
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @user = current_user

  end



  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      flash[:notice]
      render :new
    end
  end

  def index
    @books = Book.all
    @user = current_user
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    @book = Book.new


  end

  def show
    @book = Book.new
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    read_count = ReadCount.new(book_id: @book.id, user_id: current_user.id)
    read_count.save
    current_user.read_counts.create(book_id: @book.id)
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :author)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorite_path(book), method: :delete, remote: true do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to book_favorite_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/books/_list.html.erb
<%= flash[:notice] %>

<div class="container px-5 px-sm-0">
  <div class="row mt-3">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= link_to user_path(@user) do %>
        <%= image_tag @user.get_profile_image(100,100) %>
      <% end %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
          </tr>
        </tbody>
      </table>
      
      <div class="row">
        <% if current_user != @user %>
          <td><%= render "relationships/btn", user: @user, options: { class: ""} %></td>
        <% else %>
          <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        <% end %>
      </div>
      
      <div>
        <% if current_user != @user && current_user.following?(@user) && @user.following?(current_user) %>
          <td><%= link_to 'chatを始める', chat_path(@user.id), class: "ml-3" %></td>
        <% end %>
      </div>
      
      
      <h2 class="mt-3">New book</h2>
      
      <%= form_with model: Book.new, url: '/books', method: :post do |f| %>
      <div class="form-group">
        <div class="field_with_errors">
          <label for="book_title">Title</label>
        </div>
        <div class="field_with_errors">
          <%= f.text_field :title, id:"book_title", class: "form-control book_title" %>
        </div>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <div class="field_with_errors">
          <%= f.text_area :body, id:"book_body", class: "form-control book_body" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row mt-3">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <div id="error_explanation">
          <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <% end %>
        </div>
        <%= form_with model: @book do |f| %>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="book.title">Title</label>
          </div>
          <div class="field_with_errors">
          <%= f.text_field :title,  id:"book_title", class: "form-control book_title" %>
          </div>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <div class="field_with_errors">
            <%= f.text_area :body, id:"book_body", class: "form-control book_body" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
        <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <div class="error_explanation">
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
</div>

<%= render 'list',books: @books %>


        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(50,50) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td id="favorite_buttons_<%= book.id %>">
                <%= render "favorite", book: book %>
              </td>
              <td>閲覧数：<%= book.read_counts.count %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <div class="error_explanation">
    <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  </div>
</div>
<%= render 'list',books: @books %>


        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>

<%= render 'list',books: @books %>

          <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= image_tag @user.get_profile_image(100,100) %>
                  <br />
                  <%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book) %></td>
              <td><%= @book.body %></td>
              <td id="favorite_buttons_<%= @book.id %>">
                <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorite_path(@book), method: :delete, remote: true do %>
                    ♥<%= @book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorite_path(@book), method: :post, remote: true do %>
                    ♡<%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
              </td>
              <td>閲覧数：<%= @book.read_counts.count %></td>
              
              <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <td id="comment_counter">
             <%= render "book_comments/counter", book: @book %>
           </td>
        <div id="comment_index">
         <%= render "book_comments/index", book: @book %>
       </div>
      </div>
  </div>
</div>